const data = [
  {
    "id": 1,
    "make": "Tata",
    "model": "Nexon",
    "bodyType": "Compact SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 1450000,
    "mileage": 17.4,
    "safetyRating": 5,
    "features": ["Automatic gearbox", "Sunroof", "6 airbags", "Apple CarPlay"]
  },
  {
    "id": 2,
    "make": "Tata",
    "model": "Punch",
    "bodyType": "Micro SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 1050000,
    "mileage": 18.8,
    "safetyRating": 5,
    "features": ["Automatic gearbox", "6 airbags", "Apple CarPlay"]
  },
  {
    "id": 3,
    "make": "Maruti Suzuki",
    "model": "Brezza",
    "bodyType": "Compact SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 1380000,
    "mileage": 19.8,
    "safetyRating": 4,
    "features": ["Automatic gearbox", "Sunroof", "6 airbags", "Apple CarPlay"]
  },
  {
    "id": 4,
    "make": "Maruti Suzuki",
    "model": "Grand Vitara",
    "bodyType": "SUV",
    "fuelType": "Hybrid",
    "transmission": "Automatic",
    "onRoadPrice": 1850000,
    "mileage": 27.9,
    "safetyRating": 4,
    "features": ["Automatic gearbox", "Sunroof", "360 Camera", "Apple CarPlay"]
  },
  {
    "id": 5,
    "make": "Hyundai",
    "model": "Venue",
    "bodyType": "Compact SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 1450000,
    "mileage": 18.1,
    "safetyRating": 4,
    "features": ["Automatic gearbox", "Sunroof", "Apple CarPlay", "Connected Car Tech"]
  },
  {
    "id": 6,
    "make": "Hyundai",
    "model": "Creta",
    "bodyType": "SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 2200000,
    "mileage": 17.7,
    "safetyRating": 3,
    "features": ["Automatic gearbox", "Sunroof", "Ventilated Seats", "360 Camera"]
  },
  {
    "id": 7,
    "make": "Kia",
    "model": "Sonet",
    "bodyType": "Compact SUV",
    "fuelType": "Diesel",
    "transmission": "Automatic",
    "onRoadPrice": 1550000,
    "mileage": 24.1,
    "safetyRating": 3,
    "features": ["Automatic gearbox", "Sunroof", "Bose Audio", "Apple CarPlay"]
  },
  {
    "id": 8,
    "make": "Kia",
    "model": "Seltos",
    "bodyType": "SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 2350000,
    "mileage": 17.9,
    "safetyRating": 3,
    "features": ["Automatic gearbox", "Sunroof", "ADAS", "Ventilated Seats"]
  },
  {
    "id": 9,
    "make": "Mahindra",
    "model": "XUV 3XO",
    "bodyType": "Compact SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 1500000,
    "mileage": 18.2,
    "safetyRating": 5,
    "features": ["Automatic gearbox", "Sunroof", "6 airbags", "360 Camera"]
  },
  {
    "id": 10,
    "make": "Mahindra",
    "model": "Scorpio N",
    "bodyType": "SUV",
    "fuelType": "Diesel",
    "transmission": "Automatic",
    "onRoadPrice": 2650000,
    "mileage": 15.4,
    "safetyRating": 5,
    "features": ["Automatic gearbox", "6 airbags", "Sunroof", "4WD"]
  },
  {
    "id": 11,
    "make": "Mahindra",
    "model": "XUV700",
    "bodyType": "SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 3100000,
    "mileage": 16.5,
    "safetyRating": 5,
    "features": ["ADAS", "Sunroof", "360 Camera", "6 airbags"]
  },
  {
    "id": 12,
    "make": "Honda",
    "model": "City",
    "bodyType": "Sedan",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 1850000,
    "mileage": 18.4,
    "safetyRating": 5,
    "features": ["ADAS", "Sunroof", "Apple CarPlay", "6 airbags"]
  },
  {
    "id": 13,
    "make": "Honda",
    "model": "Elevate",
    "bodyType": "SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 1950000,
    "mileage": 16.9,
    "safetyRating": 5,
    "features": ["ADAS", "Sunroof", "6 airbags", "Apple CarPlay"]
  },
  {
    "id": 14,
    "make": "Toyota",
    "model": "Urban Cruiser Hyryder",
    "bodyType": "SUV",
    "fuelType": "Hybrid",
    "transmission": "Automatic",
    "onRoadPrice": 2250000,
    "mileage": 27.9,
    "safetyRating": 4,
    "features": ["Automatic gearbox", "Sunroof", "360 Camera", "Apple CarPlay"]
  },
  {
    "id": 15,
    "make": "Toyota",
    "model": "Innova Hycross",
    "bodyType": "MPV",
    "fuelType": "Hybrid",
    "transmission": "Automatic",
    "onRoadPrice": 3900000,
    "mileage": 23.2,
    "safetyRating": 5,
    "features": ["ADAS", "Sunroof", "6 airbags", "Ventilated Seats"]
  },
  {
    "id": 16,
    "make": "Volkswagen",
    "model": "Virtus",
    "bodyType": "Sedan",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 2150000,
    "mileage": 18.7,
    "safetyRating": 5,
    "features": ["Sunroof", "6 airbags", "Apple CarPlay", "Automatic gearbox"]
  },
  {
    "id": 17,
    "make": "Volkswagen",
    "model": "Taigun",
    "bodyType": "SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 2200000,
    "mileage": 18.4,
    "safetyRating": 5,
    "features": ["Sunroof", "6 airbags", "Apple CarPlay", "Automatic gearbox"]
  },
  {
    "id": 18,
    "make": "Skoda",
    "model": "Slavia",
    "bodyType": "Sedan",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 2100000,
    "mileage": 18.7,
    "safetyRating": 5,
    "features": ["Sunroof", "6 airbags", "Apple CarPlay", "Automatic gearbox"]
  },
  {
    "id": 19,
    "make": "Skoda",
    "model": "Kushaq",
    "bodyType": "SUV",
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "onRoadPrice": 2150000,
    "mileage": 18.1,
    "safetyRating": 5,
    "features": ["Sunroof", "6 airbags", "Apple CarPlay", "Automatic gearbox"]
  },
  {
    "id": 20,
    "make": "MG",
    "model": "ZS EV",
    "bodyType": "Electric SUV",
    "fuelType": "Electric",
    "transmission": "Automatic",
    "onRoadPrice": 2650000,
    "mileage": 461,
    "safetyRating": 5,
    "features": ["ADAS", "360 Camera", "Sunroof", "Apple CarPlay"]
  }
];

export default data;